// All human-readable copy, English and Polish. Numbers come from data.js; only prose lives here.
// Statements about JWST results are worded conservatively (observed / disfavoured / not ruled out).

export const COPY = {
  en: {
    meta: {
      title: 'TRAPPIST-1 Atlas',
      description: 'A true-scale 3D atlas of TRAPPIST-1, seven Earth-sized worlds around one small red star. Every planet is procedural, and the soundtrack is the system’s real orbital resonance.',
    },
    ui: {
      enterSound: 'Enter with sound',
      enterSilent: 'Enter silently',
      loading: 'Compiling seven worlds',
      ready: 'Ready',
      scrollHint: 'Scroll to travel',
      skip: 'Skip to the data',
      chapter: 'Chapter',
      explore: 'Explore',
      backToStory: 'Back to story',
      sound: 'Sound',
      distStar: 'Distance to star',
      lightDelay: 'Starlight takes',
      sizes: 'Sizes',
      trueScale: 'true scale',
      exaggerated: '×{n} exaggerated',
      artist: 'Artist’s impression. No image of these surfaces exists.',
      known: 'What we know',
      unknown: 'What we don’t',
      surface: 'As drawn here',
      standOn: 'Stand on {p}',
      lookUp: 'Look up from {p}',
      km: 'km',
      millionKm: 'M km',
      seconds: 's',
      minutes: 'min',
      days: 'd',
      hours: 'h',
      earthRadii: '× Earth',
      earthLight: '× Earth’s',
    },
    stats: {
      radius: 'Radius',
      mass: 'Mass',
      year: 'Year',
      orbit: 'Orbit',
      temp: 'Temperature',
      light: 'Starlight',
      gravity: 'Gravity',
      sky: 'Star in sky',
      skyUnit: '× the Sun’s width',
      escape: 'escape {v} km/s',
    },
    rail: { star: 'Star', chain: 'Chain', scale: 'Scale' },
    hero: {
      kicker: 'TRAPPIST-1 · Aquarius · 40.7 light-years',
      title: 'Seven worlds. One small red star.',
      sub: 'A true-scale atlas of the nearest system with seven Earth-sized planets. Scroll to fly through it, or take the controls.',
    },
    star: {
      name: 'The ember',
      kicker: 'The star',
      lede: 'TRAPPIST-1 is an M8 dwarf: 9% of the Sun’s mass, barely 1.2 times the radius of Jupiter, and a surface near 2,300 K. It gives out about 0.06% of the Sun’s light, mostly as infrared, and it will keep burning for trillions of years.',
      unknown: 'The star flares often. How much that erodes the air of the planets around it is an open question.',
      facts: [
        ['Type', 'M8 V', ''],
        ['Mass', '0.090', '× Sun'],
        ['Radius', '0.119', '× Sun'],
        ['Surface', '2,300', 'kelvin'],
        ['Output', '0.057', '% of the Sun'],
        ['Age', '7.6', 'billion years'],
        ['Spin', '3.3', 'days'],
        ['Distance', '40.7', 'light-years'],
      ],
      surface: 'A convection mosaic with cool starspots, shown deeper red than a Sun-like star.',
    },
    planets: {
      b: {
        name: 'The scorched',
        lede: 'Innermost and hottest. It circles the star every 36 hours, about 33 times closer than Mercury is to the Sun. In 2023 JWST measured its day side at roughly 230 °C, which fits bare rock with little or no atmosphere.',
        known: 'Its mass and size match a rocky planet a little denser than Earth.',
        unknown: 'Whether it holds any air at all. The day side is consistent with none.',
        surface: 'Airless, cratered basalt, faintly hot on the star-facing side.',
      },
      c: {
        name: 'The dust',
        lede: 'A near twin of b in size and density. JWST found a day side near 107 °C, too cool for a thick, Venus-like carbon dioxide atmosphere. A thinner one is not ruled out.',
        known: 'Rocky, and about as dense as b.',
        unknown: 'Whether a thin atmosphere survives the star’s flares.',
        surface: 'Dusty ochre plains with dark basaltic basins. No atmosphere drawn.',
      },
      d: {
        name: 'The veil',
        lede: 'The smallest of the inner four, and the least dense of them. It sits at the warm edge of the habitable zone, where a wet world can tip into a steam greenhouse. Early JWST results do not show a thick hydrogen atmosphere; heavier ones remain possible.',
        known: 'Density hints at more water or gas than a bare rock would hold.',
        unknown: 'What is under the sky, if there is a sky.',
        surface: 'A pale cloud deck spiralling round the point under the star.',
      },
      e: {
        name: 'The eyeball',
        lede: 'It gets about two thirds of the light Earth does, a level where liquid water is possible if an atmosphere holds the heat. Like all seven it is tidally locked: one hemisphere in endless day, the other in endless night. JWST has ruled out a thick hydrogen atmosphere; a thinner, heavier one is still being tested.',
        known: 'Its orbit sits inside the habitable zone in most models.',
        unknown: 'Whether it has any atmosphere, and so whether water can be liquid at all.',
        surface: 'One popular model: open ocean under the star, ice on the dark side, cloud swirling round the noon point.',
      },
      f: {
        name: 'The frost',
        lede: 'It gets about 37% of Earth’s light. With a thick greenhouse atmosphere it could hold liquid water; without one it would be a world of ice. Its neighbours are close enough that, at closest approach, g would look a quarter wider than our Moon does.',
        known: 'Density and size point to a rocky world, perhaps with a lot of water.',
        unknown: 'Its atmosphere, if any, has not been measured.',
        surface: 'A fractured ice shell, blue where the ice is clear.',
      },
      g: {
        name: 'The snowball',
        lede: 'The largest of the seven, 13% wider than Earth, with about a quarter of Earth’s starlight. Its year is 12 days. Any surface water would need a strong greenhouse to stay liquid.',
        known: 'Slightly larger and more massive than Earth.',
        unknown: 'Whether the large fractures we imagine here have any counterpart at all.',
        surface: 'Pale ice crossed by long dark fractures.',
      },
      h: {
        name: 'The far one',
        lede: 'The smallest and coldest, at 19 days per orbit. It was the last to be pinned down: its orbit fits the same resonant pattern as the others, and that pattern helped fix its period.',
        known: 'It is small, about three-quarters of Earth’s width, and cold.',
        unknown: 'Almost everything else. It transits rarely and is dim.',
        surface: 'Dark, tholin-stained ice with bright fresh craters.',
      },
    },
    chain: {
      name: 'The chain',
      kicker: 'The system',
      lede: 'Neighbouring planets have orbital periods in near whole-number ratios: 8:5, 5:3, 3:2, 3:2, 4:3, 3:2. This resonant chain is thought to be a fossil of the planets drifting inward together, gently, while the system was young.',
      sound: 'Turn the periods into pitch and the chain becomes a chord. Frequency ∝ 1 / period, shifted by a fixed factor into hearing range: 55, 82.5, 110, 165, 247.5, 412.5 and 660 Hz.',
      listen: 'Listen',
      standOn: 'Stand on e',
    },
    scale: {
      name: 'True scale',
      kicker: 'A warning about every picture so far',
      lede: 'To be visible, the planets were drawn 5 to 24 times too large, and the star 2.5 to 4 times. At true scale the whole system fits inside Mercury’s orbit, and its planets are specks.',
      note: 'Everything here is now at scale: the star has a radius of 13 Earths, and the planets 1.',
      mercury: 'Mercury’s orbit around the Sun, drawn at the same scale',
    },
    data: {
      title: 'The seven at a glance',
      sub: 'Values from Agol et al. 2021, as listed by the NASA Exoplanet Archive. Temperature assumes no atmosphere and zero albedo.',
      cols: ['World', 'Radius', 'Mass', 'Year', 'Orbit', 'Temp.', 'Light', 'Gravity'],
      colsUnits: ['', '× Earth', '× Earth', 'days', 'M km', 'K', '× Earth', 'g'],
      chartsTitle: 'Against Earth',
      earthMark: 'Earth = 1',
      radiusChart: 'Radius',
      lightChart: 'Starlight received',
      lightNote: 'Log scale. Earth receives 1.',
    },
    outro: {
      title: 'Now fly it yourself',
      lede: 'Drag to orbit, scroll to zoom, click a world to focus. Speed up time and the periods become rhythm. Stand on a planet and look up.',
      cta: 'Enter Explore mode',
      sources: 'Sources',
      s1: 'Gillon et al. 2017, Nature 542, 456: discovery of the seven planets.',
      s2: 'Agol et al. 2021, Planetary Science Journal 2, 1: masses, radii, orbits.',
      s3: 'Greene et al. 2023 and Zieba et al. 2023, Nature: JWST day-side temperatures of b and c.',
      s4: 'NASA Exoplanet Archive: exoplanetarchive.ipac.caltech.edu',
      note: 'Every surface, cloud and sound here is generated in your browser. Nothing is downloaded but the code. Phases at load are illustrative; periods and sizes are measured.',
      built: 'Built with three.js and WebGL2. No images, no audio files.',
    },
    explore: {
      title: 'Explore',
      hint: 'Drag to orbit · scroll to zoom · click a world',
      time: 'Time',
      paused: 'Paused',
      speed: 'speed',
      perSecond: 'days per second',
      orbits: 'Orbits',
      labels: 'Labels',
      true: 'True scale',
      clock: 'Resonance clock',
      focus: 'Focus',
      star: 'Star',
      keys: 'Space pause · [ ] speed · 1–7 worlds · 0 star · T scale · O orbits · Esc back',
      sky: 'Sky from the surface',
      skyOf: 'Sky of {p}',
      terminator: 'Twilight zone',
      substellar: 'Under the star',
      antistellar: 'Night side',
      skyNote: 'True sizes and distances. The star is fixed in this sky; neighbouring worlds sweep past. Scroll to zoom: at about 10° you can see the phase and surface of another world.',
      aim: 'Aim at the largest neighbour',
      wide: 'Wide view',
      biggest: 'Largest neighbour',
      moon: '× the Moon in our sky',
      starSize: 'Star is {n}× the Sun’s width',
      close: 'Close',
      pause: 'Pause',
      play: 'Play',
      moonWord: 'Moon',
      sunWord: 'Sun',
      day: 'Day',
      belowHorizon: 'Every neighbour is below the horizon right now',
    },
    a11y: {
      canvas: 'Interactive 3D view of the TRAPPIST-1 planetary system',
      rail: 'Chapters',
      noWebgl: 'Your browser cannot run WebGL2, so the 3D view is off. The full text and data are below.',
    },
  },

  pl: {
    meta: {
      title: 'Atlas TRAPPIST-1',
      description: 'Atlas 3D układu TRAPPIST-1 w prawdziwej skali: siedem światów wielkości Ziemi wokół jednej małej, czerwonej gwiazdy. Każda planeta jest proceduralna, a ścieżką dźwiękową jest prawdziwy rezonans orbit.',
    },
    ui: {
      enterSound: 'Wejdź z dźwiękiem',
      enterSilent: 'Wejdź bez dźwięku',
      loading: 'Kompilowanie siedmiu światów',
      ready: 'Gotowe',
      scrollHint: 'Przewiń, by lecieć',
      skip: 'Przejdź do danych',
      chapter: 'Rozdział',
      explore: 'Eksploruj',
      backToStory: 'Wróć do opowieści',
      sound: 'Dźwięk',
      distStar: 'Odległość od gwiazdy',
      lightDelay: 'Światło gwiazdy leci',
      sizes: 'Rozmiary',
      trueScale: 'prawdziwa skala',
      exaggerated: 'powiększone ×{n}',
      artist: 'Wizja artystyczna. Nikt nie widział tych powierzchni.',
      known: 'Co wiemy',
      unknown: 'Czego nie wiemy',
      surface: 'Tak jest tu narysowana',
      standOn: 'Stań na {p}',
      lookUp: 'Spójrz w niebo z {p}',
      km: 'km',
      millionKm: 'mln km',
      seconds: 's',
      minutes: 'min',
      days: 'd',
      hours: 'h',
      earthRadii: '× Ziemia',
      earthLight: '× Ziemi',
    },
    stats: {
      radius: 'Promień',
      mass: 'Masa',
      year: 'Rok',
      orbit: 'Orbita',
      temp: 'Temperatura',
      light: 'Światło gwiazdy',
      gravity: 'Grawitacja',
      sky: 'Gwiazda na niebie',
      skyUnit: '× szerokość Słońca',
      escape: 'ucieczki {v} km/s',
    },
    rail: { star: 'Gwiazda', chain: 'Łańcuch', scale: 'Skala' },
    hero: {
      kicker: 'TRAPPIST-1 · Wodnik · 40,7 roku świetlnego',
      title: 'Siedem światów. Jedna mała, czerwona gwiazda.',
      sub: 'Atlas w prawdziwej skali: najbliższy znany układ z siedmioma planetami wielkości Ziemi. Przewiń, by przez niego przelecieć, albo przejmij stery.',
    },
    star: {
      name: 'Żar',
      kicker: 'Gwiazda',
      lede: 'TRAPPIST-1 to karzeł typu M8: 9% masy Słońca, promień zaledwie 1,2 raza większy od Jowisza i powierzchnia o temperaturze około 2300 K. Świeci z mocą około 0,06% Słońca, głównie w podczerwieni, i będzie płonąć przez biliony lat.',
      unknown: 'Gwiazda często wybucha rozbłyskami. Jak bardzo niszczy to atmosfery krążących wokół niej planet, to wciąż otwarte pytanie.',
      facts: [
        ['Typ', 'M8 V', ''],
        ['Masa', '0,090', '× Słońce'],
        ['Promień', '0,119', '× Słońce'],
        ['Powierzchnia', '2300', 'kelwinów'],
        ['Moc', '0,057', '% Słońca'],
        ['Wiek', '7,6', 'mld lat'],
        ['Obrót', '3,3', 'doby'],
        ['Odległość', '40,7', 'lat świetlnych'],
      ],
      surface: 'Mozaika komórek konwekcyjnych z chłodnymi plamami, pokazana w głębszej czerwieni niż gwiazda podobna do Słońca.',
    },
    planets: {
      b: {
        name: 'Spalona',
        lede: 'Najbliższa i najgorętsza. Okrąża gwiazdę co 36 godzin, około 33 razy bliżej niż Merkury Słońca. W 2023 roku JWST zmierzył jej dzienną stronę na około 230 °C, co pasuje do gołej skały z niewielką atmosferą albo bez niej.',
        known: 'Masa i rozmiar pasują do skalistej planety nieco gęstszej od Ziemi.',
        unknown: 'Czy ma jakąkolwiek atmosferę. Pomiar dziennej strony nie wskazuje na żadną.',
        surface: 'Bezpowietrzny, pokryty kraterami bazalt, lekko rozgrzany od strony gwiazdy.',
      },
      c: {
        name: 'Pył',
        lede: 'Niemal bliźniaczka b pod względem rozmiaru i gęstości. JWST wykrył na dziennej stronie około 107 °C, zbyt mało na gęstą atmosferę z dwutlenku węgla jak na Wenus. Cieńsza nie jest wykluczona.',
        known: 'Skalista i mniej więcej tak gęsta jak b.',
        unknown: 'Czy cienka atmosfera przetrwa rozbłyski gwiazdy.',
        surface: 'Zakurzone, ochrowe równiny i ciemne baseny bazaltowe. Bez atmosfery.',
      },
      d: {
        name: 'Zasłona',
        lede: 'Najmniejsza z czterech wewnętrznych i zarazem najmniej gęsta z nich. Leży przy ciepłym brzegu ekosfery, gdzie mokry świat może przejść w parową cieplarnię. Wstępne wyniki JWST nie pokazują gęstej wodorowej atmosfery; cięższe pozostają możliwe.',
        known: 'Gęstość sugeruje więcej wody lub gazu, niż zawierałaby sama skała.',
        unknown: 'Co jest pod niebem, jeśli w ogóle jest niebo.',
        surface: 'Blada warstwa chmur skręcona spiralą wokół punktu pod gwiazdą.',
      },
      e: {
        name: 'Oko',
        lede: 'Dostaje około dwóch trzecich światła, które dociera do Ziemi. Przy takim poziomie ciekła woda jest możliwa, jeśli atmosfera utrzyma ciepło. Jak wszystkie siedem jest w rotacji synchronicznej: jedna półkula w wiecznym dniu, druga w wiecznej nocy. JWST wykluczył gęstą atmosferę wodorową; cieńsza i cięższa jest wciąż badana.',
        known: 'W większości modeli jej orbita leży w ekosferze.',
        unknown: 'Czy ma w ogóle atmosferę, a więc czy woda może być tam ciekła.',
        surface: 'Jeden z popularnych modeli: otwarty ocean pod gwiazdą, lód po stronie nocnej i chmury wirujące wokół południa.',
      },
      f: {
        name: 'Szron',
        lede: 'Dostaje około 37% światła, które dociera do Ziemi. Z gęstą atmosferą cieplarnianą mogłaby mieć ciekłą wodę, bez niej byłaby światem lodu. Sąsiedzi są tak blisko, że w największym zbliżeniu g wyglądałaby o jedną czwartą szerzej niż nasz Księżyc.',
        known: 'Gęstość i rozmiar wskazują na skalisty świat, być może z dużą ilością wody.',
        unknown: 'Jej atmosfery, jeśli istnieje, nie zmierzono.',
        surface: 'Popękana skorupa lodu, niebieska tam, gdzie lód jest czysty.',
      },
      g: {
        name: 'Śnieżna kula',
        lede: 'Największa z siedmiu, o 13% szersza od Ziemi, z około jedną czwartą ziemskiego światła. Jej rok trwa 12 dni. Woda na powierzchni potrzebowałaby silnego efektu cieplarnianego, by pozostać płynna.',
        known: 'Nieco większa i masywniejsza od Ziemi.',
        unknown: 'Czy wyobrażone tu długie szczeliny mają jakikolwiek odpowiednik.',
        surface: 'Blady lód przecięty długimi, ciemnymi szczelinami.',
      },
      h: {
        name: 'Daleka',
        lede: 'Najmniejsza i najzimniejsza, z 19 dniami na orbitę. Ostatnia, którą udało się uchwycić: jej orbita pasuje do tego samego rezonansowego wzoru co pozostałe, a wzór ten pomógł ustalić jej okres.',
        known: 'Jest mała, ma około trzy czwarte szerokości Ziemi, i zimna.',
        unknown: 'Prawie wszystko inne. Rzadko przechodzi przed gwiazdą i jest słabo widoczna.',
        surface: 'Ciemny lód zabarwiony tholinami, z jasnymi, świeżymi kraterami.',
      },
    },
    chain: {
      name: 'Łańcuch',
      kicker: 'Układ',
      lede: 'Okresy obiegu sąsiednich planet mają niemal całkowite stosunki: 8:5, 5:3, 3:2, 3:2, 4:3, 3:2. Uważa się, że ten łańcuch rezonansowy to skamielina po tym, jak planety razem i łagodnie dryfowały do środka, gdy układ był młody.',
      sound: 'Zamień okresy na wysokość dźwięku, a łańcuch stanie się akordem. Częstotliwość ∝ 1 / okres, przesunięta o stały czynnik w zakres słyszalny: 55, 82,5, 110, 165, 247,5, 412,5 i 660 Hz.',
      listen: 'Posłuchaj',
      standOn: 'Stań na e',
    },
    scale: {
      name: 'Prawdziwa skala',
      kicker: 'Ostrzeżenie o wszystkich obrazach do tej pory',
      lede: 'Żeby były widoczne, planety rysowano od 5 do 24 razy za duże, a gwiazdę 2,5 do 4 razy. W prawdziwej skali cały układ mieści się w orbicie Merkurego, a planety są pyłkami.',
      note: 'Teraz wszystko jest w skali: gwiazda ma promień 13 Ziemi, a planety po 1.',
      mercury: 'Orbita Merkurego wokół Słońca w tej samej skali',
    },
    data: {
      title: 'Siedem w skrócie',
      sub: 'Wartości z Agol i in. 2021, według NASA Exoplanet Archive. Temperatura zakłada brak atmosfery i zerowe albedo.',
      cols: ['Świat', 'Promień', 'Masa', 'Rok', 'Orbita', 'Temp.', 'Światło', 'Grawitacja'],
      colsUnits: ['', '× Ziemia', '× Ziemia', 'doby', 'mln km', 'K', '× Ziemi', 'g'],
      chartsTitle: 'W porównaniu z Ziemią',
      earthMark: 'Ziemia = 1',
      radiusChart: 'Promień',
      lightChart: 'Otrzymywane światło',
      lightNote: 'Skala logarytmiczna. Ziemia dostaje 1.',
    },
    outro: {
      title: 'Teraz poleć sam',
      lede: 'Przeciągnij, by obracać, przewiń, by przybliżyć, kliknij świat, by go objąć. Przyspiesz czas, a okresy staną się rytmem. Stań na planecie i spójrz w górę.',
      cta: 'Wejdź w tryb eksploracji',
      sources: 'Źródła',
      s1: 'Gillon i in. 2017, Nature 542, 456: odkrycie siedmiu planet.',
      s2: 'Agol i in. 2021, Planetary Science Journal 2, 1: masy, promienie, orbity.',
      s3: 'Greene i in. 2023 oraz Zieba i in. 2023, Nature: temperatury dziennej strony b i c z JWST.',
      s4: 'NASA Exoplanet Archive: exoplanetarchive.ipac.caltech.edu',
      note: 'Każda powierzchnia, chmura i dźwięk powstaje w Twojej przeglądarce. Pobierany jest tylko kod. Fazy orbit przy starcie są poglądowe; okresy i rozmiary są zmierzone.',
      built: 'Zbudowane w three.js i WebGL2. Bez obrazów, bez plików audio.',
    },
    explore: {
      title: 'Eksploracja',
      hint: 'Przeciągnij, by obracać · przewiń, by przybliżyć · kliknij świat',
      time: 'Czas',
      paused: 'Pauza',
      speed: 'prędkość',
      perSecond: 'doby na sekundę',
      orbits: 'Orbity',
      labels: 'Etykiety',
      true: 'Prawdziwa skala',
      clock: 'Zegar rezonansu',
      focus: 'Cel',
      star: 'Gwiazda',
      keys: 'Spacja pauza · [ ] prędkość · 1–7 światy · 0 gwiazda · T skala · O orbity · Esc wróć',
      sky: 'Niebo z powierzchni',
      skyOf: 'Niebo na {p}',
      terminator: 'Strefa zmierzchu',
      substellar: 'Pod gwiazdą',
      antistellar: 'Strona nocna',
      skyNote: 'Prawdziwe rozmiary i odległości. Gwiazda stoi w miejscu; sąsiednie światy przesuwają się po niebie. Przewiń, by przybliżyć: przy około 10° widać fazę i powierzchnię innego świata.',
      aim: 'Celuj w największego sąsiada',
      wide: 'Szeroki kadr',
      biggest: 'Największy sąsiad',
      moon: '× Księżyc na naszym niebie',
      starSize: 'Gwiazda ma {n}× szerokość Słońca',
      close: 'Zamknij',
      pause: 'Pauza',
      play: 'Odtwarzaj',
      moonWord: 'Księżyca',
      sunWord: 'Słońca',
      day: 'Doba',
      belowHorizon: 'Wszyscy sąsiedzi są teraz pod horyzontem',
    },
    a11y: {
      canvas: 'Interaktywny widok 3D układu planetarnego TRAPPIST-1',
      rail: 'Rozdziały',
      noWebgl: 'Twoja przeglądarka nie obsługuje WebGL2, więc widok 3D jest wyłączony. Cały tekst i dane są poniżej.',
    },
  },
};

export const LANGS = ['en', 'pl'];

export function detectLang() {
  try {
    const saved = localStorage.getItem('t1-lang');
    if (LANGS.includes(saved)) return saved;
  } catch {}
  const nav = (navigator.languages && navigator.languages[0]) || navigator.language || 'en';
  return nav.toLowerCase().startsWith('pl') ? 'pl' : 'en';
}
